version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: lsc_image_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${IMAGES_PATH}:/usr/share/nginx/html:ro
    ports:
      - "${IMAGES_SERVER_PORT}:80"
    restart: always
