services:
  solr:
    image: solr:9.6
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/var/solr  # Maps a local directory `./solrdata` to the Solr data directory
    command:
      - solr-precreate
      - mycore
    restart: unless-stopped

