version: '3.8'
services:
  clip:
    build: docker/open_clip
    deploy:
      resources:
        limits:
          memory: 32G
    shm_size: '32G'
    volumes:
      - .:/app
      - ${IMAGES_PATH}:/images
      - ${CSV_FILE}:/faiss_index.csv
      - ./hf-cache:/hf-cache
    ports:
      - "${CLIP_PORT}:8002"
    command: ["python", "clip.py"]
    environment:
      - HF_HOME=/hf-cache