version: '3.8'
services:
  extract:
    build: docker/open_clip
    deploy:
      resources:
        limits:
          memory: 16G
    shm_size: '16G'
    volumes:
      - .:/app
      - ./../hf-cache:/hf-cache
    command: ["python", "extract-image-features.py", "images", "test.csv"]
    environment:
      - HF_HOME=/hf-cache