version: '3.8'
services:
  extract:
    build: docker/open_clip
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
      - .:/app
    command: ["python", "extract-image-features.py"]