version: '3.8'
services:
  analysis:
    build: docker/analysis
    deploy:
      resources:
        limits:
          memory: 16G
    shm_size: '16G'
    volumes:
      - .:/app
      - ${IMAGES_PATH}:/images
      - ${IMAGES_TO_PROCESS}:/images_to_process
      - ${HF_HOME}:/hf-cache
    command: ["python", "extract-image-features.py"]
    environment:
      - HF_HOME=/hf-cache